### ISSUE TITLE
Markdown rendered wrong when message is shortened 

### ISSUE THREAD

**Issue by Zigolox** [digitalungdom-se/digitalungdom.se#10]
When viewed in agora the markdown element is cut-off making the text non bold

https://digitalungdom.se/agora/h/general/comments/gR5Dvya/vad_tror_ni_kommer_bli_nsta_hypade_sak_efter_ai

**Comment by kelszo** [comment]
Confirmed

![image](https://user-images.githubusercontent.com/41587072/68802734-bfa25200-065e-11ea-9e53-fe940e6b7528.png)
![image](https://user-images.githubusercontent.com/41587072/68802699-af8a7280-065e-11ea-9c61-ec5afc8e206e.png)

**Comment by Nautman** [comment]
The error is caused by the truncating function, that simply takes the first `n` chars of the string. This means that the error will also cut some emojis off in the middle, since emojis are several bytes long.

The truncating function is probably useful in several applications and components. Perhaps it is best to modularise and create a standard function or React component?

Currently, we are using [react-markdown](https://github.com/rexxars/react-markdown) to render the markdown. However, we may switch soon in the future once we will start using [Draftjs](https://github.com/facebook/draft-js).

Could someone try to review the current libraries and see if they are desirable?

A quick internet search found these:
* [ellipsis.js](https://github.com/glinford/ellipsis.js)
* [React Truncate Markup](https://github.com/parsable/react-truncate-markup)
* [react-truncate-html](https://github.com/jariz/react-truncate-html)
* [React-Truncate](https://github.com/One-com/react-truncate)

**Comment by charlesmaddock** [comment]
> The error is caused by the truncating function, that simply takes the first `n` chars of the string. This means that the error will also cut some emojis off in the middle, since emojis are several bytes long.
> 
> The truncating function is probably useful in several applications and components. Perhaps it is best to modularise and create a standard function or React component?
> 
> Currently, we are using [react-markdown](https://github.com/rexxars/react-markdown) to render the markdown. However, we may switch soon in the future once we will start using [Draftjs](https://github.com/facebook/draft-js).
> 
> Could someone try to review the current libraries and see if they are desirable?
> 
> A quick internet search found these:
> 
> * [ellipsis.js](https://github.com/glinford/ellipsis.js)
> * [React Truncate Markup](https://github.com/parsable/react-truncate-markup)
> * [react-truncate-html](https://github.com/jariz/react-truncate-html)
> * [React-Truncate](https://github.com/One-com/react-truncate)

I have tried playing around a bit with the modules you presented and have failed so far. The modules aren't able to truncate ReactMarkdown. Can you think of any way to solve this? Or should we just try and move on to draft.js?

**Comment by Nautman** [comment]
This works better in the rewrite. Can you take a look and see if you think it's good enough? @Zigolox
