### ISSUE TITLE
Link for verifying email

### ISSUE THREAD

**Issue by Nautman** [digitalungdom-se/digitalungdom.se#40]
There needs to be a page at `/verify/:token`. It needs to communicate to the API the verifying token.

There are a couple of uncertainties at the moment:

1. Should the user be able to resend the verification email?
    a) Should there be a spam limit? Currently any user can see if someone is unverified by logging in with their username / email. They don't need to have the correct password.

2. Should we cover an edge case in which the user already has verified their email or if their token is invalid?

**Comment by Nautman** [comment]
As always, create a branch and a pull request. (I might regret this later since I'll probably be the one implementing the feature. I need to make sure I get it reviewed fast! :D )

**Comment by Nautman** [comment]
I am wondering if the user needs to login after they have verified their email or if a session is automatically created for them? @digitalungdom-se/back-end-team

**Comment by Zigolox** [comment]
Concerning you uncertainties:

1. I think there someone should be able to resend the verification email which also should generate a new login token. There is however a question if the user should be able to change the email address to something new before verifying by only supplying the username. I think this feature if implemented should only be done with password because otherwise a malicious user can change email address and become the owner to the account granting them access to personal information.
a) I think a spam-limit should be implemented as for all other emails.  There probably shouldn't be a difference between a registered account and an un-verified one so a login with only username shouldn't give error specific error. I also think we need to implement periodic purging of non-verified users because otherwise usernames can be "locked".

2. I think this is low priority and could just be an short error message.

> I am wondering if the user needs to login after they have verified their email or if a session is automatically created for them? @digitalungdom-se/back-end-team

This should be done automatically but i don't know of the current implementation. @kelszo knows more.

**Comment by Nautman** [comment]
> > I am wondering if the user needs to login after they have verified their email or if a session is automatically created for them? @digitalungdom-se/back-end-team
> 
> This should be done automatically but i don't know of the current implementation. @kelszo knows more.

A session is automatically created. [Here is the source code.](https://github.com/digitalungdom-se/user-api/blob/466e43e47e7d1c7f97a3c2952db03480c205903c/src/api/controllers/signup.ts)

**Comment by Nautman** [comment]
Please see my pull request.

**Comment by Nautman** [comment]
Pull request has been merged. I'm closing this issue. If you think anything needs to change or have any comments, please open a new issue or reopen this one.
